accounts_app/urls.py
from django.urls import path
from . import views

app_name = 'accounts_app'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('profile/', views.profile_view, name='profile'),  # базовый профиль
    path('profile/<str:username>/', views.profile_view, name='user_profile'),  # профиль по username
    path('change-password/', views.change_password, name='change_password'),
    path('password-reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

api/urls.py
from rest_framework.documentation import include_docs_urls
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import PostViewSet, CategoryViewSet, TagViewSet, UserViewSet, RegisterView

app_name = 'api'

router = DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'posts', PostViewSet)
router.register(r'categories', CategoryViewSet)
router.register(r'tags', TagViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('auth/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('auth/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('auth/register/', RegisterView.as_view(), name='register'),
]

blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from python_blog.views import main, about


urlpatterns = [

    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('accounts_app.urls', namespace='accounts_app'), name='accounts'),
    path('', main, name="main"),
    path('about/', about, name="about"),
    path('posts/', include('python_blog.urls', namespace='blog')),
    path('api/', include('api.urls', namespace='api')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

python_blog/urls.py
from django.urls import path
from .views import (
    PostListView, PostDetailView, PostCreateView,
    PostUpdateView, CategoryListView, CategoryDetailView,
    TagListView, TagDetailView
)

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='blog'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
    path('post/<slug:slug>/', PostDetailView.as_view(), name='post_detail'),
    path('post/<slug:slug>/update/', PostUpdateView.as_view(), name='post_update'),
    path('categories/', CategoryListView.as_view(), name='catalog_categories'),
    path('categories/<slug:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('tags/', TagListView.as_view(), name='catalog_tags'),
    path('tags/<slug:slug>/', TagDetailView.as_view(), name='tag_detail'),
]

python_blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from unidecode import unidecode


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название категории')
    slug = models.SlugField(max_length=250, unique=True, blank=True, verbose_name='Слаг')
    description = models.TextField(blank=True, null=True, default='Без описания', verbose_name='Описание')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(str(self.name)))
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:category_detail', kwargs={'category_slug': self.slug})

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Tag(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название тега')
    slug = models.SlugField(max_length=250, unique=True, verbose_name='Слаг')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(str(self.name)))
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:tag_detail', kwargs={'tag_slug': self.slug})

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'


class Post(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название поста')
    text = models.TextField(verbose_name='Текст поста')
    slug = models.SlugField(unique=True, blank=True, verbose_name='Слаг')
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name='Автор')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, verbose_name='Категория')
    tags = models.ManyToManyField(Tag, blank=True, verbose_name='Теги')
    is_published = models.BooleanField(default=False, verbose_name='Опубликовано')
    views = models.PositiveIntegerField(default=0, verbose_name='Просмотры')
    likes = models.PositiveIntegerField(default=0, verbose_name='Лайки')
    published_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    updated_date = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(str(self.title)))
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-published_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

python_blog/forms.py
from django import forms
from .models import Post, Tag, Category


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].empty_label = 'Выберите категорию'

    # Поле для ввода тегов через запятую
    tags = forms.CharField(required=False, help_text='Введите теги через запятую')

    class Meta:
        model = Post
        fields = ['title', 'text', 'category', 'tags']
        widgets = {
            'text': forms.Textarea(attrs={'rows': 10}),
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'})
        }

    def clean_tags(self):
        # Очистка и валидация поля тегов
        tags_string = self.cleaned_data.get('tags', '')
        if tags_string:
            # Разбиваем строку по запятым и удаляем пробелы
            tag_names = [tag.strip() for tag in tags_string.split(',') if tag.strip()]
            return tag_names
        return []

    def save(self, commit=True):
        # Сохраняем пост без коммита в базу
        post = super().save(commit=False)

        if commit:
            # Сохраняем пост
            post.save()

            # Обработка тегов
            post.tags.clear()  # Очищаем существующие теги
            tag_names = self.cleaned_data.get('tags', [])
            # Создаем или получаем теги и добавляем их к посту
            for tag_name in tag_names:
                tag, _ = Tag.objects.get_or_create(name=tag_name)
                post.tags.add(tag)

        return post

python_blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F, Q
from django.urls import reverse_lazy
from .models import Post, Category, Tag
from .forms import PostForm

def main(request):
    return render(request, 'main.html')


def about(request):
    context = {
        "title": "О нас",
        "text": "Страница с информацией о нас",
    }
    return render(request, 'about.html', context)

class PostListView(ListView):
    model = Post
    template_name = 'python_blog/blog.html'
    context_object_name = 'posts'
    paginate_by = 6

    def get_queryset(self):
        query = self.request.GET.get('query')
        if query:
            queries = Q()
            if self.request.GET.get('category') == 'on':
                queries |= Q(category__name__icontains=query)
            if self.request.GET.get('title') == 'on':
                queries |= Q(title__icontains=query)
            if self.request.GET.get('text') == 'on':
                queries |= Q(text__icontains=query)
            if self.request.GET.get('tags') == 'on':
                queries |= Q(tags__name__icontains=query)
            return Post.objects.filter(queries).distinct() if queries else Post.objects.none()
        return Post.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('query')
        context['categories'] = Category.objects.all()
        return context

class PostDetailView(DetailView):
    model = Post
    template_name = 'python_blog/post_detail.html'
    context_object_name = 'post'

    def get_object(self):
        obj = super().get_object()
        Post.objects.filter(pk=obj.pk).update(views=F('views') + 1)
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['related_posts'] = Post.objects.filter(category=self.object.category).exclude(pk=self.object.pk)[:3]
        return context

    def get_queryset(self):
        return Post.objects.select_related('category', 'author').prefetch_related('tags')

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'python_blog/post_form.html'
    success_url = reverse_lazy('blog:blog')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'python_blog/post_form.html'
    success_url = reverse_lazy('blog:blog')

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user)

class CategoryListView(ListView):
    model = Category
    template_name = 'python_blog/catalog_categories.html'
    context_object_name = 'categories'

class CategoryDetailView(DetailView):
    model = Category
    template_name = 'python_blog/category_detail.html'
    context_object_name = 'category'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.filter(category=self.object)
        return context

class TagListView(ListView):
    model = Tag
    template_name = 'python_blog/catalog_tags.html'
    context_object_name = 'tags'

class TagDetailView(DetailView):
    model = Tag
    template_name = 'python_blog/tag_detail.html'
    context_object_name = 'tag'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.filter(tags=self.object)
        return context

python_blog/templates/python_blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        {% comment %}{% endcomment %}
        {% include "python_blog/menu_include.html" %}
    </header>
    <main>{% block content %}{% endblock %}</main>
    <footer>{% block footer %}{% endblock %}</footer>
</body>
</html>

python_blog/templates/python_blog/blog.html
{% extends 'base.html' %}

{% block title %}Статьи{% endblock %}

{% block content %}
    <!-- Поисковая форма -->
    <div class="search-form-container mt-5">
        <h2 class="text-center mb-4">Поиск статей</h2>
        <form class="search-form" method="get">
            <div class="input-group mb-3">
                <input type="text" name="query" class="form-control" placeholder="Введите ваш поисковый запрос"
                       aria-label="Поисковый запрос" value="{{ query|default:'' }}">
                <button class="btn btn-primary" type="submit">Поиск</button>
            </div>

            <div class="form-check-container mt-3">
                <h5>Фильтры поиска:</h5>
                <ul class="list-unstyled">
                    <li class="form-check">
                        <input class="form-check-input" type="checkbox" name="category" id="category-checkbox"
                               {% if request.GET.category == 'on' %}checked{% endif %}>
                        <label class="form-check-label" for="category-checkbox">Категория</label>
                    </li>
                    <li class="form-check">
                        <input class="form-check-input" type="checkbox" name="title" id="title-checkbox"
                               {% if request.GET.title == 'on' %}checked{% endif %}>
                        <label class="form-check-label" for="title-checkbox">Заголовок</label>
                    </li>
                    <li class="form-check">
                        <input class="form-check-input" type="checkbox" name="text" id="text-checkbox"
                               {% if request.GET.text == 'on' %}checked{% endif %}>
                        <label class="form-check-label" for="text-checkbox">Текст</label>
                    </li>
                    <li class="form-check">
                        <input class="form-check-input" type="checkbox" name="tags" id="tags-checkbox"
                               {% if request.GET.tags == 'on' %}checked{% endif %}>
                        <label class="form-check-label" for="tags-checkbox">Теги</label>
                    </li>
                </ul>
            </div>
        </form>
    </div>

    <div class="container">
        <div class="blog-header mb-5">
            <div class="d-flex justify-content-between align-items-center mb-4">
                <h2>{% if query %}Результаты поиска{% else %}Последние статьи{% endif %}</h2>
                <a href="{% url 'blog:post_create' %}" class="btn btn-primary">
                    <i class="fas fa-plus"></i> Создать пост
                </a>
            </div>

            {% if posts %}
                <div class="row g-4">
                    {% for post in posts %}
                        <div class="col-md-6 col-lg-4">
                            <article class="card h-100 post-card shadow-sm">
                                {% if post.image %}
                                    <img src="{{ post.image.url }}" class="card-img-top" alt="{{ post.title }}">
                                {% endif %}
                                <div class="card-body">
                                    <h5 class="card-title">{{ post.title }}</h5>
                                    <p class="card-text">{{ post.text|truncatewords:20 }}</p>

                                    <div class="mb-3">
                                        {% if post.category %}
                                            <span class="tag-badge bg-primary text-white me-2">{{ post.category.name }}</span>
                                        {% endif %}
                                        {% for tag in post.tags.all %}
                                            <span class="tag-badge bg-secondary text-white me-2">{{ tag.name }}</span>
                                        {% endfor %}
                                    </div>

                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="stats text-muted">
                                            <i class="fas fa-eye"></i> {{ post.views }}
                                            <i class="fas fa-heart ms-2"></i> {{ post.likes }}
                                        </div>
                                        <a href="{{ post.get_absolute_url }}" class="btn btn-outline-primary custom-btn">
                                            Читать <i class="fas fa-arrow-right ms-2"></i>
                                        </a>
                                    </div>
                                </div>
                                <div class="card-footer text-muted">
                                    <small>{{ post.published_date|date:"d.m.Y" }}</small>
                                </div>
                            </article>
                        </div>
                    {% endfor %}
                </div>

                {% if page_obj.has_other_pages %}
                    {% include 'includes/pagination.html' %}
                {% endif %}
            {% else %}
                <div class="alert alert-info text-center">
                    {% if query %}
                        По вашему запросу ничего не найдено
                    {% else %}
                        Нет доступных постов
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

python_blog/templates/python_blog/catalog_categories.html
{% extends 'base.html' %}

{% block title %}Категории{% endblock %}

{% block content %}
<div class="categories-container">
    <h1 class="text-center mb-4">Категории блога</h1>
    <div class="row">
        {% for category in categories %}
            <div class="col-md-4 mb-4">
                <div class="category-card card h-100">
                    <div class="card-body">
                        <h3 class="card-title">{{ category.name }}</h3>
                        <p class="card-text">Постов: {{ category.posts.count }}</p>
                        <a href="{% url 'blog:category_detail' category.slug %}" class="btn btn-primary">
                            Перейти к постам
                        </a>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="col-12">
                <p class="text-center">Категории пока не добавлены</p>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

python_blog/templates/python_blog/catalog_posts.html
{% extends 'base.html' %}

{% block title %}Каталог постов{% endblock %}

{% block content %}
<div class="posts-container">
    <h1 class="text-center mb-4">Все посты</h1>
    <div class="row">
        {% for post in posts %}
            <div class="col-md-4 mb-4">
                <div class="post-card card h-100">
                    {% if post.image %}
                        <img src="{{ post.image.url }}" class="card-img-top" alt="{{ post.title }}">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ post.title }}</h5>
                        <p class="card-text">{{ post.text|truncatewords:30 }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Читать далее</a>
                            <small class="text-muted">{{ post.created_at|date:"d.m.Y" }}</small>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="col-12">
                <p class="text-center">Посты пока не добавлены</p>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

python_blog/templates/python_blog/catalog_tags.html
{% extends 'base.html' %}

{% block title %}Теги{% endblock %}

{% block content %}
<div class="tags-container">
    <h1 class="text-center mb-4">Теги блога</h1>
    <div class="row">
        {% for tag in tags %}
            <div class="col-md-3 mb-3">
                <div class="tag-card card h-100">
                    <div class="card-body">
                        <h4 class="card-title">{{ tag.name }}</h4>
                        <p class="card-text">Постов: {{ tag.posts.count }}</p>
                        <a href="{% url 'blog:tag_detail' tag.slug %}" class="btn btn-primary">
                            Смотреть посты
                        </a>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="col-12">
                <p class="text-center">Теги пока не добавлены</p>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

python_blog/templates/python_blog/category_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Category Detail</title>
</head>
<body>
    <h1>Детальная информация о категории</h1>
    <p>Категория: {{ category_slug }}</p>
</body>
</html>

python_blog/templates/python_blog/category_include.html
<div class="category-card">
    <h3>{{ category.name }}</h3>
    <p>Слаг: {{ category.slug }}</p>
    <a href="{% url 'blog:category_detail' category.slug %}">Перейти к категории</a>
</div>

python_blog/templates/python_blog/nav_include.html
<nav>
    <ul>
        {% for item in menu_items %}
        <li>
            <a href="{% url item.url_name %}">{{ item.title}}</a>
        </li>
        {% endfor %}
    </ul>
</nav>

python_blog/templates/python_blog/post_detail.html
{% extends 'base.html' %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <div class="post-detail">
        <div class="card">
            {% if post.image %}
                <img src="{{ post.image.url }}" class="card-img-top" alt="{{ post.title }}">
            {% endif %}
            <div class="card-body">
                <h1 class="card-title">{{ post.title }}</h1>
                <div class="post-meta mb-3">
                    <span class="author">Автор: <a
                            href="{% url 'accounts_app:user_profile' post.author.username %}">{{ post.author.username }}</a></span>
                    |
                    <span class="date">{{ post.created_at|date:"d.m.Y" }}</span> |
                    <span class="views">Просмотры: {{ post.views }}</span>
                </div>
                <div class="post-category mb-2">
                    Категория: <a
                        href="{% url 'blog:category_detail' post.category.slug %}">{{ post.category.name }}</a>
                </div>
                <div class="post-tags mb-3">
                    Теги:
                    {% for tag in post.tags.all %}
                        <a href="{% url 'blog:tag_detail' tag.slug %}" class="badge bg-secondary">{{ tag.name }}</a>
                    {% endfor %}
                </div>
                <div class="post-content">
                    {{ post.text|linebreaks }}
                </div>
            </div>
        </div>

        {% if related_posts %}
            <div class="related-posts mt-4">
                <h3>Похожие статьи</h3>
                <div class="row">
                    {% for related_post in related_posts %}
                        <div class="col-md-4">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">{{ related_post.title }}</h5>
                                    <a href="{{ related_post.get_absolute_url }}" class="btn btn-primary">Читать</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

python_blog/templates/python_blog/post_form.html
{% extends 'base.html' %}

{% block title %}
    {% if post %}Редактирование поста{% else %}Создание нового поста{% endif %}
{% endblock %}

{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow-sm">
                <div class="card-header bg-primary text-white">
                    <h2 class="h4 mb-0">
                        {% if post %}
                            <i class="fas fa-edit"></i> Редактирование поста
                        {% else %}
                            <i class="fas fa-plus-circle"></i> Создание нового поста
                        {% endif %}
                    </h2>
                </div>
                <div class="card-body">
                    <form method="post" class="post-form">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.as_p }}
                        </div>
                        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                            <a href="{% url 'blog:blog' %}" class="btn btn-secondary me-md-2">
                                <i class="fas fa-times"></i> Отмена
                            </a>
                            <button type="submit" class="btn btn-primary">
                                {% if post %}
                                    <i class="fas fa-save"></i> Сохранить изменения
                                {% else %}
                                    <i class="fas fa-plus"></i> Создать пост
                                {% endif %}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

python_blog/templates/python_blog/post_preview_include.html
<div class="post-card">
    <div class="card-body">
        <h5 class="card-title">{{ post.title }}</h5>
        <p class="card-text">{{ post.text|truncatewords:30 }}</p>
        
        <div class="post-meta">
            {% if post.category %}
                <a href="{{ post.category.get_absolute_url }}" class="category-badge">
                    {{ post.category.name }}
                </a>
            {% endif %}
            
            {% for tag in post.tags.all %}
                <a href="{{ tag.get_absolute_url }}" class="tag-badge">
                    {{ tag.name }}
                </a>
            {% endfor %}
        </div>

        <div class="post-footer">
            <div class="stats">
                <span><i class="fas fa-eye"></i> {{ post.views }}</span>
                <span><i class="fas fa-calendar"></i> {{ post.published_date|date:"d.m.Y" }}</span>
            </div>
            <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Читать</a>
        </div>
    </div>
</div>

python_blog/templates/python_blog/tag_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Tag Detail</title>
</head>
<body>
    <h1>Детальная информация о TAG</h1>
    <h2>TAG: {{ tag_slug }}</h2>
</body>
</html>